services:
  vllm:
    build:
      context: .
    container_name: vllm
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "58000:8000"
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - MODEL=${MODEL}
      - GPU_MEMORY_UTILIZATION=${GPU_MEMORY_UTILIZATION:-0.9}
      - MAX_NUM_SEQS=${MAX_NUM_SEQS:-8}
      - MAX_MODEL_LEN=${MAX_MODEL_LEN:-32768}
    ipc: host
    restart: unless-stopped
    networks:
      - vllm-network
    command: >
      --model ${MODEL}
      --trust-remote-code
      --max-model-len ${MAX_MODEL_LEN}
      --gpu-memory-utilization ${GPU_MEMORY_UTILIZATION}
      --max-num-seqs ${MAX_NUM_SEQS}

#   prometheus:
#     image: prom/prometheus:latest
#     container_name: prometheus
#     volumes:
#       - ./prometheus/config:/etc/prometheus
#       - prometheus-data:/prometheus
#     ports:
#       - 59090:9090
#     command:
#       - '--storage.tsdb.path=/prometheus'
#       - '--config.file=/etc/prometheus/prometheus.yml'
#     depends_on:
#       - vllm
#       - node_exporter
#     restart: unless-stopped
#     networks:
#       - vllm-network

#   grafana:
#     image: grafana/grafana:latest
#     container_name: grafana
#     ports:
#       - 53000:3000
#     volumes:
#       - grafana-data:/var/lib/grafana
#       - ./grafana/provisioning/:/etc/grafana/provisioning/
#     depends_on:
#       - prometheus
#     restart: unless-stopped
#     networks:
#       - vllm-network

#   node_exporter:
#     image: prom/node-exporter:latest
#     container_name: node_exporter
#     volumes:
#       - /proc:/host/proc:ro
#       - /sys:/host/sys:ro
#       - /:/rootfs:ro
#     command:
#       - '--path.procfs=/host/proc'
#       - '--path.rootfs=/rootfs'
#       - '--path.sysfs=/host/sys'
#       - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
#     ports:
#       - 59100:9100
#     restart: unless-stopped
#     networks:
#       - vllm-network

# volumes:
#   grafana-data:
#   prometheus-data:

networks:
  vllm-network:
    driver: bridge